export const tooltipMap = {
  "Local SEO Schema": "Indicates the presence of SEO schema data on the webpage.",
  "SSL Certificate": "checks whether the webpage uses SSL (Secure Sockets Layer).",
  "SEO Friendly": "Indicates whether the webpage is considered SEO-friendly or not.",
  "Google Tag Manager": "Indicates whether Google Tag Manager is present on the webpage.",
  "Meta Description": "It represents a brief summary or description of the webpage's content.",
  "Tag Data": "Information about various HTML tags on a webpage.",
  "Text HTML Ratio":"The ratio of text length to HTML length on the webpage, providing an indication of how much of the page is actual text content.",
  "Favicon URL":"Represents the URL of the favicon, the small icon displayed in the browser tab.",
  "XML Site Map URL":"XML sitemaps help search engines crawl and index the site's pages.",
  "Flash Data":"Flash data is temporary information passed between server and client, used once (e.g., for success or error messages) and then discarded.",
  "Meta Title":"Title of the webpage.",
  "Images with no Alt tags":"Contains URLs of images with no alt text.",
  "Internal Links":"Internal links point to other pages within the same website.",
  "External Links":"External links point to pages on different websites.",
  "Broken Page Links":"Broken links may lead to non-existent or inaccessible content.",
  "Web Page":"The URL of the webpage under consideration.",
  "Domain Authority": "A score from 1 to 100 representing the likelihood that this root domain will rank well in search engine result pages.",
  "Page Authority":"A score from 1 to 100 representing the likelihood that this page will rank well in search engine result pages.",
  "Link Propensity":"A score from 0 to 1 indicating the likelihood of the target root domain to link out to other root domains. This is currently calculated as the ratio.",
  "Spam Score":"A spam score indicates the likelihood that a website or email is perceived as spam, evaluated based on content, links, and common spam triggers.",
  "Http Code":"The HTTP status code returned by the server, indicating the outcome of the request made to the webpage.",
  "Pages to Page":"The number of unique pages currently linking to this page. Pages that link to themselves do not contribute to this count.",
  "Performance Score":"A score indicating the overall performance of the webpage on mobile devices.",
  "First Contentful Paint":"The time taken for the first piece of content to be painted on the screen during page load.",
  "Largest Contentful Paint":"The time taken for the largest content element to be painted on the screen during page load.",
  "Speed Index":"A metric representing how quickly content is visually displayed during page load.",
  "Time To Interactive":"The time taken for the webpage to become fully interactive and responsive to user input.",
  "Total Blocking Time":"The total time during which users may experience delays in interactivity due to main thread blocking.",
};
